---
title: "TidyTuesday"
output: html_document
date: "2022-08-12"
---

```{r}
# devtools::install_github("dill/emoGG")
library(tidyverse)
library(showtext)
library(lubridate)
library(ggtext)
library(emoGG)
```

```{r}
font_add_google('Pacifico', 'pacifico')
showtext_auto()
```

```{r}
tuesdata = tidytuesdayR::tt_load(2022, week = 32)
wheels = tuesdata$wheels
```

```{r}
country_names = 
  wheels %>% 
  group_by(country) %>% 
  summarise(n = n()) %>% 
  filter(n >= 5) %>% 
  select(country) %>% 
  pull()

plot_data = wheels %>% 
  filter(country %in% country_names & !is.na(opened) & !is.na(height)) %>% 
  mutate(years = year(opened),
         height_in_m = height * 0.3048) 
```

```{r}
title_text = 'Development of ferris wheel heights'
subtitle_text = 'between 1880 and 2020 in China, Japan and the US'
caption_text = 'TidyTuesday 2022 - Week 32 | Data: Ferris Wheels\nGraphic: @itsLauBa7'

ggplot(plot_data, aes(years, height_in_m)) +
  geom_emoji(emoji="1f3a1", size=0.15) +
  facet_wrap(~country) +
  labs(x='Years', y='Height (in m)', title = title_text, subtitle = subtitle_text, caption = caption_text) +
  scale_x_continuous(limits = c(1880, 2020)) +
  scale_y_continuous(limits = c(0, 200)) +
  theme_bw() +
  theme(text = element_text(family = 'pacifico', color='magenta4'),
        plot.title = element_text(size=20, face = 'bold'),
        plot.subtitle = element_text(size=15),
        plot.caption = element_text(size=8),                             
        panel.grid = element_blank(),
        panel.border = element_rect(color='magenta4'),
        strip.background = element_rect(fill='gray95', color='magenta4'),
        strip.text = element_text(color='magenta4', size=15),
        panel.background = element_rect(fill = 'gray95'),
        plot.background = element_rect(fill = 'gray95'),
        axis.text = element_text(color='magenta4', size=10, family='pacifico'),
        axis.title = element_text(size=15),
        axis.ticks = element_line(color='magenta4')
        )
```


